apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webserver-deploy
  name: webserver-deploy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: webserver-deploy
  template:
    metadata:
      labels:
        app: webserver-deploy
    spec:
      containers:
      - image: {{ .Values.webserver_image }}
        name: webserver
        ports:
        - containerPort: 80
        resources: {}
        envFrom: 
          - configMapRef: 
              name: server-config
        env:
          - name: MYSQL_PASSWORD
            # value: Clarusway_1
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_PASSWORD

        # - name: MYSQL_DATABASE
        #   value: phonebook
        # - name: MYSQL_USER
        #   value: clarus
        # - name: MYSQL_DATABASE_HOST
        #   value: mysql
      

